

// LOCALHOST ### 
GET http://localhost:8080/contacts

// LOCALHOST 
### 
GET http://localhost:8080/professional

###
GET http://localhost:8080/contacts/6325d9779a0a46103327dae1

###
GET http://localhost:8080/contacts/6325d9779a0a46103327dae1

###
GET http://localhost:8080/contacts/6325d9779a0a46103327dae1


# Add new Contact information
### 
POST http://localhost:8080/contacts  HTTP/1.1
content-type: application/json

{
    "firstname":"Burnie",
    "lastname":"Nawn", 
    "email":"burnie@nawn.com", 
    "favorite_Color":"blue", 
    "birthdate":"06/19/1970"
}

# Delete _id contact
###
DELETE  http://localhost:8080/contacts/632d31893bc6071cf735a016 HTTP/1.1

### 
PUT http://localhost:8080/contacts/632d31893bc6071cf735a016 HTTP/1.1
content-type: application/json

{
    "firstname":"Burnie",
    "lastname":"Nawn", 
    "email":"burnie@nawn.com", 
    "favorite_Color":"blue", 
    "birthdate":"06/19/1970"
}


// PRODUCTION Deploy ###

###
GET https://cse342-lesson2.onrender.com/professional

###
GET https://cse342-lesson2.onrender.com/contacts

###
GET https://cse342-lesson2.onrender.com/contacts/6325d9779a0a46103327dae1


# Add new Contact information
### 
POST https://cse342-lesson2.onrender.com/contacts  HTTP/1.1
content-type: application/json

{
    "firstname":"Burnie",
    "lastname":"Nawn", 
    "email":"burnie@nawn.com", 
    "favorite_Color":"blue", 
    "birthdate":"06/19/1970"
}

# Delete _id contact
###
DELETE  https://cse342-lesson2.onrender.com/contacts/632d31893bc6071cf735a016 HTTP/1.1

### 
PUT https://cse342-lesson2.onrender.com/contacts/contacts/632d31893bc6071cf735a016 HTTP/1.1
content-type: application/json

{
    "firstname":"Burnie",
    "lastname":"Nawn", 
    "email":"burnie@nawn.com", 
    "favorite_Color":"blue", 
    "birthdate":"06/19/1970"
}
