

// LOCALHOST ### 
GET http://localhost:8080/contacts

// LOCALHOST 
### 
GET http://localhost:8080/professional

###
GET http://localhost:8080/contacts/632d351e1a824b4863bcc83f

###
GET http://localhost:8080/contacts/6325d9779a0a46103327dae1

###
GET http://localhost:8080/contacts/6325d9779a0a46103327dae1


# Add new Contact information
### 
POST http://localhost:8080/contacts  HTTP/1.1
content-type: application/json

{
    "firstname":"Burning",
    "lastname":"Nawn", 
    "email":"burnie@nawn.com", 
    "favourite_color":"blue", 
    "birthdate":"06/19/1970"
}

# Delete _id contact
###
DELETE  http://localhost:8080/contacts/632d437d960458e663ceb332 HTTP/1.1
content-type: application/json
### 
PUT http://localhost:8080/contacts/632d437d960458e663ceb332 HTTP/1.1
content-type: application/json

{
    "firstname":"Burnie",
    "lastname":"Nawn", 
    "email":"burnie@nawn.com", 
    "favourite_color":"blue", 
    "birthdate":"06/19/1970"
}


// PRODUCTION Deploy ###

###
GET https://cse341-lesson3.onrender.com/professional

###
GET https://cse341-lesson3.onrender.com/contacts

###
GET https://cse341-lesson3.onrender.com/contacts/6325d9779a0a46103327dae1


# Add new Contact information
### 
POST https://cse341-lesson3.onrender.com/contacts  HTTP/1.1
content-type: application/json

{
    "firstname":"Burnie",
    "lastname":"Nawn", 
    "email":"burnie@nawn.com", 
    "favourite_color":"blue", 
    "birthdate":"06/19/1970"
}

# Delete _id contact
###
DELETE  https://cse341-lesson3.onrender.com/contacts/632d43e5288e216a0f36b3e3 HTTP/1.1

### 
PUT https://cse341-lesson3.onrender.com/contacts/632d43e5288e216a0f36b3e3 HTTP/1.1
content-type: application/json

{
    "firstname":"Augustine",
    "lastname":"Nawn", 
    "email":"burnie@nawn.com", 
    "favourite_color":"blue", 
    "birthdate":"06/19/1970"
}
